### PR TITLE
added de10lite board definition file

### PR DESCRIPTION
**Pull request by teezzan**
Hello,
I added the board definition of the popular de10-lite to the repository. I tested and it works with the blinky example. Please review. 

Regards,
Taiwo

### CODE REVIEW

**Comment by whitequark** [comment]
Please file this PR over [here](https://github.com/nmigen/nmigen-boards).

**Comment by teezzan** [comment]
Ok thanks. I guess I should close this then.

**Comment by sbourdeauducq** [comment]
@teezzan This repository is still maintained.

**Comment by teezzan** [comment]
@sbourdeauducq What should I do? I deleted the branch and fork already.

**Comment by sbourdeauducq** [comment]
Nothing - I also merged your commit here. This is just FYI.

**Pull request closed without merging**
